AllCops:
  Exclude:

Layout/LineLength:
  Exclude:

Metrics/BlockLength:
  Exclude:
    - signature_dfe.gemspec
    - spec/signature_dfe_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/signature_dfe/ssl.rb