AllCops:
  Exclude:

Layout/LineLength:
  Exclude:

Metrics/BlockLength:
  Exclude:


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20